import { IsNotEmpty, IsString, IsOptional, IsArray, IsBoolean, IsEmail, IsObject } from 'class-validator';

export class FlyerDto {
  @IsOptional()
  @IsString()
  id?: string; // Unique ID for easy removal

  @IsNotEmpty()
  @IsString()
  name!: string;

  @IsNotEmpty()
  @IsString()
  flyer!: string;
}

export class DocumentDto {
  @IsOptional()
  @IsString()
  id?: string; // Unique ID for easy removal (auto-generated)

  @IsNotEmpty()
  @IsString()
  name!: string;

  @IsNotEmpty()
  @IsString()
  document!: string;
}

export class EventImageDto {
  @IsOptional()
  @IsString()
  id?: string; // Unique ID for easy removal (auto-generated)

  @IsNotEmpty()
  @IsString()
  name!: string;

  @IsNotEmpty()
  @IsString()
  eventImage!: string;
}

// Booth banner is now a simple array of strings (images, videos, links)
// Example: ["image1.jpg", "image2.jpg", "video.mp4", "http://url.com"]

export class ExhibitorDto {
  @IsNotEmpty()
  @IsString()
  companyName!: string;

  @IsOptional()
  @IsString()
  companyDescription?: string;

  @IsOptional()
  @IsBoolean()
  isActive?: boolean;

  // Add new boothNumber field
  @IsOptional()
  @IsString()
  boothNumber?: string;

  // Booth banner - array of objects with value (image, video, or link)
  // IDs are auto-generated by database in booth_banners table
  // Example: [{"value": "image1.jpg"}, {"value": "http://url.com"}]
  // Or simple strings: ["image1.jpg", "http://url.com"] (will be converted)
  @IsOptional()
  @IsArray()
  boothBanner?: Array<{ value: string } | string>;

  // Add new fields: email, mobile, UEN, and logo
  @IsNotEmpty()
  @IsEmail()
  email!: string;

  @IsOptional()
  @IsString()
  mobile?: string;

  @IsOptional()
  @IsString()
  uen?: string;

  @IsOptional()
  @IsString()
  logo?: string;

  @IsOptional()
  @IsString()
  website?: string;

  @IsOptional()
  @IsString()
  facebookUrl?: string;

  @IsOptional()
  @IsString()
  instagramUrl?: string;

  @IsOptional()
  @IsString()
  linkedinUrl?: string;

  @IsOptional()
  @IsString()
  xUrl?: string;

  // Updated flyers structure - array of objects with name and flyer
  @IsOptional()
  @IsArray()
  flyers?: FlyerDto[];

  // Comma-separated names for uploaded flyers (form-data)
  @IsOptional()
  @IsString()
  flyerNames?: string;

  @IsOptional()
  @IsString()
  promotionalOfferNote?: string;

  // Updated documents structure - array of objects with name and document
  @IsOptional()
  @IsArray()
  documents?: DocumentDto[];

  // Comma-separated names for uploaded documents (form-data)
  @IsOptional()
  @IsString()
  documentNames?: string;

  // Updated event images structure - array of objects with name and eventImage
  @IsOptional()
  @IsArray()
  eventImages?: EventImageDto[];

  // Comma-separated names for uploaded event images (form-data)
  @IsOptional()
  @IsString()
  eventImageNames?: string;

  // For handling existing files during update
  @IsOptional()
  @IsArray()
  originalFlyers?: FlyerDto[];

  @IsOptional()
  @IsArray()
  originalDocuments?: DocumentDto[];

  @IsOptional()
  @IsArray()
  originalEventImages?: EventImageDto[];
}
