export const AUTH_DATA = 'AUTH_DATA';
export const USER_LIST = 'USER_LIST';
export const EVENT_LIST = 'EVENT_LIST';
export const EVENT_BY_ID = 'EVENT_BY_ID';
export const GALLERY_LIST = 'GALLERY_LIST';
export const PARTICIPATED_EVENTS = 'PARTICIPATED_EVENTS';
export const UPCOMING_EVENT_LIST = 'UPCOMING_EVENT_LIST';
export const ORDER_LIST = 'ORDER_LIST';
export const WITHDRAWAL_LIST = 'WITHDRAWAL_LIST';
export const SPEAKER_LIST = 'SPEAKER_LIST';
export const TERMS_CONDITIONS = 'TERMS_CONDITIONS';
export const PRIVACY_POLICY = 'PRIVACY_POLICY';

export const EXHIBITOR_LIST = 'EXHIBITOR_LIST';
export const EXHIBITOR_BY_ID = 'EXHIBITOR_BY_ID';
export const CREATE_EXHIBITOR = 'CREATE_EXHIBITOR';
export const UPDATE_EXHIBITOR = 'UPDATE_EXHIBITOR';
export const DELETE_EXHIBITOR = 'DELETE_EXHIBITOR';
export const FETCH_PROMOTIONAL_OFFERS = 'FETCH_PROMOTIONAL_OFFERS';
export const CREATE_PROMOTIONAL_OFFER = 'CREATE_PROMOTIONAL_OFFER';
export const UPDATE_PROMOTIONAL_OFFER = 'UPDATE_PROMOTIONAL_OFFER';
export const DELETE_PROMOTIONAL_OFFER = 'DELETE_PROMOTIONAL_OFFER';
export const GET_PROMOTIONAL_OFFERS_BY_EXHIBITOR = 'GET_PROMOTIONAL_OFFERS_BY_EXHIBITOR';
export const ALL_PROMOTIONAL_OFFERS = 'ALL_PROMOTIONAL_OFFERS';
export const PROMOTIONAL_OFFER_BY_ID = 'PROMOTIONAL_OFFER_BY_ID';

// Category Action Types
export const CATEGORY_LIST = 'CATEGORY_LIST';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

// Speaker Action Types
export const CREATE_SPEAKER = 'CREATE_SPEAKER';
export const UPDATE_SPEAKER = 'UPDATE_SPEAKER';
export const DELETE_SPEAKER = 'DELETE_SPEAKER';

// Banner Action Types
export const GET_BANNERS = 'GET_BANNERS';
export const GET_BANNER_EVENTS = 'GET_BANNER_EVENTS';
export const UPLOAD_BANNERS = 'UPLOAD_BANNERS';
export const UPLOAD_BANNER_EVENTS = 'UPLOAD_BANNER_EVENTS';
export const DELETE_BANNER_IMAGE = 'DELETE_BANNER_IMAGE';
export const DELETE_BANNER_EVENT_IMAGE = 'DELETE_BANNER_EVENT_IMAGE';
export const CLEAR_ALL_BANNERS = 'CLEAR_ALL_BANNERS';
export const CLEAR_ALL_BANNER_EVENTS = 'CLEAR_ALL_BANNER_EVENTS';
export const SET_BANNER_LOADING = 'SET_BANNER_LOADING';
export const SET_BANNER_ERROR = 'SET_BANNER_ERROR';

// Gallery Action Types
export const GALLERY_BY_ID = 'GALLERY_BY_ID';
export const ALL_GALLERIES = 'ALL_GALLERIES';
