// User Action Types
export const USER_LIST = 'USER_LIST';
export const USER_LOADING = 'USER_LOADING';
export const USER_ERROR = 'USER_ERROR';
export const CREATE_USER = 'CREATE_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const USER_BY_ID = 'USER_BY_ID';

// Auth Action Types
export const AUTH_DATA = 'AUTH_DATA';
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_ERROR = 'AUTH_ERROR';

// Loading Action Types for all reducers
export const EVENT_LOADING = 'EVENT_LOADING';
export const ORDER_LOADING = 'ORDER_LOADING';
export const SPEAKER_LOADING = 'SPEAKER_LOADING';
export const EXHIBITOR_LOADING = 'EXHIBITOR_LOADING';

export const BANNER_LOADING = 'BANNER_LOADING';
export const GALLERY_LOADING = 'GALLERY_LOADING';
export const CATEGORY_LOADING = 'CATEGORY_LOADING';
export const SETTINGS_LOADING = 'SETTINGS_LOADING';
export const WITHDRAW_LOADING = 'WITHDRAW_LOADING';
export const PROMOTIONAL_OFFER_LOADING = 'PROMOTIONAL_OFFER_LOADING';

// Error Action Types for all reducers
export const EVENT_ERROR = 'EVENT_ERROR';
export const ORDER_ERROR = 'ORDER_ERROR';
export const SPEAKER_ERROR = 'SPEAKER_ERROR';
export const EXHIBITOR_ERROR = 'EXHIBITOR_ERROR';
export const BANNER_ERROR = 'BANNER_ERROR';
export const GALLERY_ERROR = 'GALLERY_ERROR';
export const CATEGORY_ERROR = 'CATEGORY_ERROR';
export const SETTINGS_ERROR = 'SETTINGS_ERROR';
export const WITHDRAW_ERROR = 'WITHDRAW_ERROR';

export const EVENT_LIST = 'EVENT_LIST';
export const EVENT_BY_ID = 'EVENT_BY_ID';
export const GALLERY_LIST = 'GALLERY_LIST';
export const PARTICIPATED_EVENTS = 'PARTICIPATED_EVENTS';
export const UPCOMING_EVENT_LIST = 'UPCOMING_EVENT_LIST';
export const ORDER_LIST = 'ORDER_LIST';
export const WITHDRAWAL_LIST = 'WITHDRAWAL_LIST';
export const SPEAKER_LIST = 'SPEAKER_LIST';
export const TERMS_CONDITIONS = 'TERMS_CONDITIONS';
export const PRIVACY_POLICY = 'PRIVACY_POLICY';

export const EXHIBITOR_LIST = 'EXHIBITOR_LIST';
export const EXHIBITOR_BY_ID = 'EXHIBITOR_BY_ID';
export const CREATE_EXHIBITOR = 'CREATE_EXHIBITOR';
export const UPDATE_EXHIBITOR = 'UPDATE_EXHIBITOR';
export const DELETE_EXHIBITOR = 'DELETE_EXHIBITOR';
export const FETCH_PROMOTIONAL_OFFERS = 'FETCH_PROMOTIONAL_OFFERS';
export const CREATE_PROMOTIONAL_OFFER = 'CREATE_PROMOTIONAL_OFFER';
export const UPDATE_PROMOTIONAL_OFFER = 'UPDATE_PROMOTIONAL_OFFER';
export const DELETE_PROMOTIONAL_OFFER = 'DELETE_PROMOTIONAL_OFFER';
export const GET_PROMOTIONAL_OFFERS_BY_EXHIBITOR = 'GET_PROMOTIONAL_OFFERS_BY_EXHIBITOR';
export const ALL_PROMOTIONAL_OFFERS = 'ALL_PROMOTIONAL_OFFERS';
export const PROMOTIONAL_OFFER_BY_ID = 'PROMOTIONAL_OFFER_BY_ID';

// Category Action Types
export const CATEGORY_LIST = 'CATEGORY_LIST';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

// Speaker Action Types
export const CREATE_SPEAKER = 'CREATE_SPEAKER';
export const UPDATE_SPEAKER = 'UPDATE_SPEAKER';
export const DELETE_SPEAKER = 'DELETE_SPEAKER';

// Banner Action Types
export const GET_BANNERS = 'GET_BANNERS';
export const GET_BANNER_EVENTS = 'GET_BANNER_EVENTS';
export const UPLOAD_BANNERS = 'UPLOAD_BANNERS';
export const UPLOAD_BANNER_EVENTS = 'UPLOAD_BANNER_EVENTS';
export const DELETE_BANNER_IMAGE = 'DELETE_BANNER_IMAGE';
export const DELETE_BANNER_EVENT_IMAGE = 'DELETE_BANNER_EVENT_IMAGE';
export const CLEAR_ALL_BANNERS = 'CLEAR_ALL_BANNERS';
export const CLEAR_ALL_BANNER_EVENTS = 'CLEAR_ALL_BANNER_EVENTS';
export const SET_BANNER_LOADING = 'SET_BANNER_LOADING';
export const SET_BANNER_ERROR = 'SET_BANNER_ERROR';

// Gallery Action Types
export const GALLERY_BY_ID = 'GALLERY_BY_ID';
export const ALL_GALLERIES = 'ALL_GALLERIES';

// QA Action Types
export const QA_LOADING = 'QA_LOADING';
export const QA_ERROR = 'QA_ERROR';
export const QA_QUESTIONS_LIST = 'QA_QUESTIONS_LIST';
export const QA_QUESTION_BY_ID = 'QA_QUESTION_BY_ID';
export const ANSWER_QUESTION = 'ANSWER_QUESTION';
export const PIN_QUESTION = 'PIN_QUESTION';
export const UNPIN_QUESTION = 'UNPIN_QUESTION';
export const LIKE_QUESTION = 'LIKE_QUESTION';
export const UNLIKE_QUESTION = 'UNLIKE_QUESTION';
export const UPDATE_QUESTION = 'UPDATE_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const CLEAR_QA_ERROR = 'CLEAR_QA_ERROR';

// Polling Action Types
export const POLLING_LOADING = 'POLLING_LOADING';
export const POLLING_ERROR = 'POLLING_ERROR';
export const POLLING_LIST = 'POLLING_LIST';
export const POLL_BY_ID = 'POLL_BY_ID';
export const CREATE_POLL = 'CREATE_POLL';
export const UPDATE_POLL = 'UPDATE_POLL';
export const DELETE_POLL = 'DELETE_POLL';
export const TOGGLE_POLL_LIVE = 'TOGGLE_POLL_LIVE';
export const POLL_RESULTS = 'POLL_RESULTS';
export const POLL_VOTES = 'POLL_VOTES';
export const CLEAR_POLLING_ERROR = 'CLEAR_POLLING_ERROR';