// Matches backend Industry enum (users.entity.ts)
export const INDUSTRY_OPTIONS = [
  { value: 'Accounting', label: 'Accounting' },
  { value: 'Administration & Office Support', label: 'Administration & Office Support' },
  { value: 'Advertising, Arts & Media', label: 'Advertising, Arts & Media' },
  { value: 'Banking & Financial Services', label: 'Banking & Financial Services' },
  { value: 'Call Centre & Customer Service', label: 'Call Centre & Customer Service' },
  { value: 'Community Services & Development', label: 'Community Services & Development' },
  { value: 'Construction', label: 'Construction' },
  { value: 'Consulting & Strategy', label: 'Consulting & Strategy' },
  { value: 'Design & Architechture', label: 'Design & Architecture' },
  { value: 'Education & Training', label: 'Education & Training' },
  { value: 'Engineering', label: 'Engineering' },
  { value: 'Farming, Animals & Conservation', label: 'Farming, Animals & Conservation' },
  { value: 'Government & Defence', label: 'Government & Defence' },
  { value: 'Healthcare & Medical', label: 'Healthcare & Medical' },
  { value: 'Hospitality & Tourism', label: 'Hospitality & Tourism' },
  { value: 'Human Resources & Recruitment', label: 'Human Resources & Recruitment' },
  { value: 'Information & Communication Technology', label: 'Information & Communication Technology' },
  { value: 'Insurance & Superannuation', label: 'Insurance & Superannuation' },
  { value: 'Legal', label: 'Legal' },
  { value: 'Manufacturing, Transport & Logistics', label: 'Manufacturing, Transport & Logistics' },
  { value: 'Marketing & Communications', label: 'Marketing & Communications' },
  { value: 'Mining, Resources & Energy', label: 'Mining, Resources & Energy' },
  { value: 'Real Estate & Property', label: 'Real Estate & Property' },
  { value: 'Retail & Consumer Products', label: 'Retail & Consumer Products' },
  { value: 'Sales', label: 'Sales' },
  { value: 'Science & Technology', label: 'Science & Technology' },
  { value: 'Sport & Recreation', label: 'Sport & Recreation' },
  { value: 'Trades & Services', label: 'Trades & Services' },
  { value: 'Others', label: 'Others' },
];
